FROM alpine:3.16

RUN apk upgrade -Ua
RUN apk add nginx tini-static

COPY nginx-server.conf /etc/nginx/http.d/default.conf

ENTRYPOINT ["/sbin/tini-static", "--", "/usr/sbin/nginx", "-g", "daemon off;"]