# Generated by Django 4.0.4 on 2022-06-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('smiles', models.CharField(max_length=500)),
                ('inchi_key', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('collection', models.ManyToManyField(to='molecule_admin.collection')),
            ],
        ),
        migrations.AddConstraint(
            model_name='molecule',
            constraint=models.UniqueConstraint(fields=('name', 'inchi_key'), name='unique-molecule-constraint'),
        ),
    ]
